### ISSUE TITLE
ねこ画像判定APIで正常な画像と判定されるが画像アップロードAPIではエラーになってしまう現象の原因調査と修正

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-api-archived#47]
# Doneの定義
- 補足情報に記載してある画像（3.7MB）がアップロード出来ない原因が判明し必要に応じて修正用のissueが作成されている事（このissueの見積もり内で解決しそうであればこのissueで解決してもOK）

 # 補足情報

以下の画像を利用。

Doneの定義にも書いてあるが https://github.com/nekochans/lgtm-cat-image-recognition に定義されているねこ画像判定APIだと問題ないが画像アップロードAPIの場合は500エラーを返してしまう。

![mop](https://user-images.githubusercontent.com/11032365/168945770-df68010f-69cd-40cd-86bc-f8e1c0184589.png)

```
echo '{"image" : "'"$( base64 ./mop.png)"'", "imageExtension": ".png"}' | \
curl -v -X POST -H "Content-Type: application/json" \
-H "Authorization: Bearer 発行したアクセストークン" \
-d @- https://image-recognition-api.lgtmeow.com/cat-images/validation-results | jq
```

```
{
  "isAcceptableCatImage": true
}
```

同じAPI GatewayV2を使っているのでpayloadサイズの限界とは違うと思うので原因を調査したほうが良さそう。

またこの現象が解消する事でユーザーがより大きなサイズの画像をアップロード出来るようになるのでその意味でも解決する価値はそれなりにあると考えている。

**Comment by keitakn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/lgtm-cat-602a31ca1eebd0000ff95261/issues/nekochans/lgtm-cat-api/47?planning-poker) with ZenHub @kobayashi-m42

**Comment by kobayashi-m42** [comment]
@keitakn 調査タスクだから大きめのポイントが良いかと思ったけれど、13だと大きすぎるかも...
適当なポイントに設定してもらえると🙏

**Comment by keitakn** [comment]
@kobayashi-m42 確かに厄介そうな問題だからポイントは大きめでもいいかもね🐱

間を取って8にしようと思う！

**Comment by keitakn** [comment]
こちら何故か解消されていた、、、AWSの内部仕様が変わって大きい画像を受け付けるようになったのだろうか🐱？？

とりあえず問題なさそうなのでClose！

[![LGTMeow](https://lgtm-images.lgtmeow.com/2022/09/06/17/be7b3f0f-208d-4c7d-bffb-e2ef34b78632.webp)](https://lgtmeow.com)
