### ISSUE TITLE
mockの生成ライブラリ moq を導入する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-api-archived#72]
# Doneの定義
- [matryer/moq](https://github.com/matryer/moq) が導入され、既存の mock コードが moq によって自動生成されたコードに置き換わっていること
- moq による mock の自動生成の方法が README に記載されていること

**Comment by keitakn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/lgtm-cat-602a31ca1eebd0000ff95261/issues/nekochans/lgtm-cat-api/72?planning-poker) with Zenhub @kobayashi-m42
